// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bysxovfxcsxyoqsedbpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5c3hvdmZ4Y3N4eW9xc2VkYnB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNTAzMTUsImV4cCI6MjA1MzcyNjMxNX0.qTNae8PgMzU4cMAierZ52zEczP1Q8taJRSiWlfvvSqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);