// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbgsuhzvomkzkduizrvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZ3N1aHp2b21remtkdWl6cnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNDg2OTAsImV4cCI6MjA1MzcyNDY5MH0.vu-N9hMEzJPc_4BGZtiZnTOnMvK3EsBzFWKGqEf6y7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);